import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import { NextThemeProvider } from "@/components/themeProvider";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import NextAuthSessionProvider from "@/context/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dharamshala Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {" "}
        <NextAuthSessionProvider>
          <NextThemeProvider>
            <Theme accentColor="blue" panelBackground="translucent">
              <Toaster position="top-right" />
              <NavBar />
              {children}
              <Footer />
            </Theme>
          </NextThemeProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
